language: python
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode9.4
      language: generic
      env: TOXENV=py36
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate
install:
  - pip install -r requirements.txt
#  此处需要加下面一行，不然Travis打出来的包不能运行：https://github.com/pypa/setuptools/issues/1963
  - pip install --upgrade 'setuptools<45.0.0'
before_script:
  - python CICDEnviromentScript.py ${tapd_user} ${tapd_password}
script:
  - pyinstaller -F -n dtemail ./wu/__main__.py
after_success:
  - |
    case "${TRAVIS_OS_NAME}" in
      osx)   export TARGET=macosx ;;
      linux) export TARGET=linux ;;
      *)     exit 1 ;;
    esac
  - cp dist/dtemail dtemail-${TARGET}
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: i4wzd13g+J78XBtElcQacAnHWttwMJwv8c0BfEjD5IKSd7rO8/DfZfBJXeQH2nv69Phs3zfT5ubEGG/KuXwctQ0dVLKJN9EPj5rN5sy6ZIMke51mQBM58tav9zzrOPFYXT+nxbN0oQNzgB9/PdSEC1bfDg1aKSZWMvUQErKb2uEPV98QWUN83aC8g26QXMPYJm1m8EmWKPeSiI+evXKEbgyRDdFWg0y1LVscxfD2LBQAbJp/FmsGttNSjeA+KiUAhZfwl8RW7GLLmMy6tw7BuN3shTCZbdsYFS8CxpvpNuKSh1gpKc2rDHkE32q7/hbDG479zB+qMucyJIWKxOjBy+zDppjMBfcmQL8dL6+RP/z6Ubk2/0iu5tPSbRLjBO09eXOkxNXOh6e7w2b/QsT9EOxcFSfeJJtGYK91akVWtah6cilNWfYbbDKnhnaLD0TXvHFlGy7TKOO/A3CQyKICdOYt86tnYdiUZtSe27X5SQhAHpBvC9FmooamGsXsvqxqvZux5XWU/PgeQaDUW6w6eWDrvn633uhnOzHPWxRrkxVFIO2LWvX+ifIOqjPPvjFF4r/aEEq1atzZd5BFkpZ9KgkqsRDxCPJpqWb2ux1VaNdxRl0xouhS9HuHqo9JY6sMc+uh5j8nKD06H5KfJzUce480KjyVW4IqdIuf7B0f3Ko=
  file: dtemail-${TARGET}
  on:
    tags: true
    repo: wuseal/DT-Email-Tool
